In [1]:
#import this before other imports
from sklearnex import patch_sklearn,unpatch_sklearn

patch_sklearn()
#unpatch_sklearn()

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from urllib.parse import urlparse
from tld import get_tld
import re
from sklearn.model_selection import train_test_split
import seaborn as sb
import warnings
warnings.filterwarnings('ignore')
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multiclass import OneVsOneClassifier
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import f1_score,log_loss,precision_score,recall_score,make_scorer,accuracy_score
import json

In [61]:
l1 = pd.read_csv("FinalDataset/URL/Benign_list_big_final.csv", header=None)
l1

                                                       0
0      http://1337x.to/torrent/1048648/American-Snipe...
1      http://1337x.to/torrent/1110018/Blackhat-2015-...
2      http://1337x.to/torrent/1122940/Blackhat-2015-...
3      http://1337x.to/torrent/1124395/Fast-and-Furio...
4      http://1337x.to/torrent/1145504/Avengers-Age-o...
...                                                  ...
35373  https://lastpass.com/signup2.php?ac=1&from_uri...
35374  https://lastpass.com/signup2.php?ac=1&from_uri...
35375  https://lastpass.com/signup2.php?ac=1&from_uri...
35376  https://lastpass.com/signup2.php?ac=1&from_uri...
35377  https://asana.com/guide/videos/%22//fast.wisti...

[35378 rows x 1 columns]

In [62]:
l1['result'] = [0 for _ in range(l1.shape[0])]
l1

                                                       0  result
0      http://1337x.to/torrent/1048648/American-Snipe...       0
1      http://1337x.to/torrent/1110018/Blackhat-2015-...       0
2      http://1337x.to/torrent/1122940/Blackhat-2015-...       0
3      http://1337x.to/torrent/1124395/Fast-and-Furio...       0
4      http://1337x.to/torrent/1145504/Avengers-Age-o...       0
...                                                  ...     ...
35373  https://lastpass.com/signup2.php?ac=1&from_uri...       0
35374  https://lastpass.com/signup2.php?ac=1&from_uri...       0
35375  https://lastpass.com/signup2.php?ac=1&from_uri...       0
35376  https://lastpass.com/signup2.php?ac=1&from_uri...       0
35377  https://asana.com/guide/videos/%22//fast.wisti...       0

[35378 rows x 2 columns]

In [63]:
l2 = pd.read_csv("FinalDataset/URL/DefacementSitesURLFiltered.csv", header=None)
l2['result'] = [1 for _ in range(l2.shape[0])]
l3 = pd.read_csv("FinalDataset/URL/Malware_dataset.csv", header=None)
l3['result'] = [1 for _ in range(l3.shape[0])]
l4 = pd.read_csv("FinalDataset/URL/phishing_dataset.csv", header=None)
l4['result'] = [1 for _ in range(l4.shape[0])]
l5 = pd.read_csv("FinalDataset/URL/spam_dataset.csv", header=None)
l5['result'] = [1 for _ in range(l5.shape[0])]

In [64]:
data = [l1,l2,l3,l4,l5]
dataset = pd.concat(data, ignore_index=True)
dataset = dataset.rename({0: 'url'}, axis=1)
dataset

                                                      url  result
0       http://1337x.to/torrent/1048648/American-Snipe...       0
1       http://1337x.to/torrent/1110018/Blackhat-2015-...       0
2       http://1337x.to/torrent/1122940/Blackhat-2015-...       0
3       http://1337x.to/torrent/1124395/Fast-and-Furio...       0
4       http://1337x.to/torrent/1145504/Avengers-Age-o...       0
...                                                   ...     ...
165361    http://archive.salisburyjournal.co.uk/2001/3/7/       1
165362  http://astore.amazon.co.uk/allezvinsfrenchr/de...       1
165363  http://archive.thisischeshire.co.uk/2000/1/14/...       1
165364  http://applerugs.co.uk/rugs/product_info.php?p...       1
165365  http://allgirltogaparty.co.uk/gallery2/main.ph...       1

[165366 rows x 2 columns]

In [65]:
vectorizer = CountVectorizer(analyzer='char')
x = vectorizer.fit_transform(dataset['url'])
x.shape

(165366, 133)

In [66]:
lr = SVC()

In [67]:
scoring = {'accuracy': make_scorer(accuracy_score),
           'precision': make_scorer(precision_score),
           'recall': make_scorer(recall_score),
           'f1': make_scorer(f1_score),
           'log_loss': make_scorer(log_loss)}

In [68]:
scores = cross_validate(lr, x, dataset['result'], cv=5,scoring=scoring,return_train_score=True)
scores

{'fit_time': array([23.50668669, 26.61165476, 25.27531576, 25.83736086, 17.29294968]),
 'score_time': array([1.68429279, 1.54149461, 1.83409572, 1.69735694, 1.48609185]),
 'test_accuracy': array([0.92807039, 0.96592387, 0.97795785, 0.94896139, 0.80948205]),
 'train_accuracy': array([0.9854413 , 0.98303009, 0.98145782, 0.98395229, 0.98662061]),
 'test_precision': array([0.92573633, 0.97974537, 0.99424928, 0.99422623, 0.86840235]),
 'train_precision': array([0.99196954, 0.99019098, 0.9900388 , 0.99031566, 0.99370194]),
 'test_recall': array([0.98772983, 0.97684348, 0.9776128 , 0.94053389, 0.8929533 ]),
 'train_recall': array([0.98948937, 0.9882009 , 0.98633536, 0.98925858, 0.98924897]),
 'test_f1': array([0.95572883, 0.97829227, 0.98586086, 0.96663504, 0.88050672]),
 'train_f1': array([0.9907279 , 0.98919494, 0.98818361, 0.98978684, 0.99147046]),
 'test_log_loss': array([2.4844106 , 1.17696069, 0.76131242, 1.76281463, 6.58034176]),
 'train_log_loss': array([0.50284484, 0.586126  , 0.64043028, 0.55427443, 0.46211179])}

In [69]:
print("The Fit Time is: ",scores['fit_time'].mean())
print("\n")
print("The Score Time is: ",scores['score_time'].mean())
print("\n")
print("The Train Accuracy score is: ",scores['train_accuracy'].mean())
print("\n")
print("The Train F1 score is: ",scores['train_f1'].mean())
print("\n")
print("The Train Precision score is: ",scores['train_precision'].mean())
print("\n")
print("The Train Recall score is: ",scores['train_recall'].mean())
print("\n")
print("The Train Log Loss is: ",scores['train_log_loss'].mean())
print("\n")
print("The Test Accuracy score is: ",scores['test_accuracy'].mean())
print("\n")
print("The Test F1 score is: ",scores['test_f1'].mean())
print("\n")
print("The Test Precision score is: ",scores['test_precision'].mean())
print("\n")
print("The Test Recall score is: ",scores['test_recall'].mean())
print("\n")
print("The Test Log Loss is: ",scores['test_log_loss'].mean())
print("\n")

The Fit Time is:  23.704793548583986


The Score Time is:  1.6486663818359375


The Train Accuracy score is:  0.9841004217022767


The Train F1 score is:  0.9898727485669738


The Train Precision score is:  0.9912433830204274


The Train Recall score is:  0.9885066361452871


The Train Log Loss is:  0.5491574688941145


The Test Accuracy score is:  0.9260791094222622


The Test F1 score is:  0.9534047447984234


The Test Precision score is:  0.9524719115501794


The Test Recall score is:  0.9551346600221817


The Test Log Loss is:  2.5531680178245773

## Multi-Class Classification

In [3]:
l2=pd.read_csv("FinalDataset/URL/DefacementSitesURLFiltered.csv", header=None)
l2['result'] = [1 for _ in range(l2.shape[0])]
l2['type'] = 'Defacement'
l2

                                                       0  result        type
0            http://www.sinduscongoias.com.br/index.html       1  Defacement
1      http://www.sinduscongoias.com.br/index.php/ins...       1  Defacement
2      http://www.sinduscongoias.com.br/index.php/ins...       1  Defacement
3      http://www.sinduscongoias.com.br/index.php/ins...       1  Defacement
4      http://www.sinduscongoias.com.br/index.php/ins...       1  Defacement
...                                                  ...     ...         ...
96452  http://www.laurenzano.com.ar/index.php?option=...       1  Defacement
96453  http://www.laurenzano.com.ar/templates/laurenz...       1  Defacement
96454  http://www.laurenzano.com.ar/templates/laurenz...       1  Defacement
96455                 http://www.laurenzano.com.ar/x.txt       1  Defacement
96456          http://www.emotionalassets.com/sejeal.jpg       1  Defacement

[96457 rows x 3 columns]

In [4]:
l3=pd.read_csv("FinalDataset/URL/Malware_dataset.csv", header=None)
l3['result'] = [2 for _ in range(l3.shape[0])]
l3['type'] = 'Malware'
l3

                                                       0  result     type
0      http://gzzax.livechatvalue.com/chat/chatClient...       2  Malware
1      http://gzzax.livechatvalue.com/chat/chatClient...       2  Malware
2      http://gzzax.livechatvalue.com/chat/chatClient...       2  Malware
3      http://gzzax.livechatvalue.com/chat/chatClient...       2  Malware
4      http://mtsx.com.cn/UploadFiles/2011-08/admin/%...       2  Malware
...                                                  ...     ...      ...
11561  http://www.plastischechirurgie.net/gesicht/fac...       2  Malware
11562  http://www.plastischechirurgie.net/haartranspl...       2  Malware
11563  http://www.plastischechirurgie.net/korper/gyna...       2  Malware
11564  http://dl.get1993desk.com/n/50517366/RealPlaye...       2  Malware
11565  http://fb.com.accounts.login.userid.492739.fbs...       2  Malware

[11566 rows x 3 columns]

In [5]:
l4=pd.read_csv("FinalDataset/URL/phishing_dataset.csv", header=None)
l4['result'] = [3 for _ in range(l4.shape[0])]
l4['type'] = 'Phishing'
l4

                                                      0  result      type
0     http://v2.email-marketing.adminsimple.com/trac...       3  Phishing
1     http://bid.openx.net/json?amp;amp;amp;amp;cid;...       3  Phishing
2     http://webmail2.centurytel.net/hwebmail/servic...       3  Phishing
3     http://www.google.com.ng/imgres?imgurl=http://...       3  Phishing
4     http://webmail2.centurytel.net/hwebmail/servic...       3  Phishing
...                                                 ...     ...       ...
9960              http://highedgesolar.com/nw/includes/       3  Phishing
9961              http://jimfangimporters.yolasite.com/       3  Phishing
9962              http://liuheng.chengxuren.com/Images/       3  Phishing
9963              http://mcnaotempreco.net/site/portal/       3  Phishing
9964              http://missionaryfilms.org/index.html       3  Phishing

[9965 rows x 3 columns]

In [6]:
l5=pd.read_csv("FinalDataset/URL/spam_dataset.csv", header=None)
l5['result'] = [4 for _ in range(l5.shape[0])]
l5['type'] = 'Spam'
l5

                                                       0  result  type
0      http://astore.amazon.co.uk/allezvinsfrenchr/de...       4  Spam
1      http://archive.salisburyjournal.co.uk/2007/3/6...       4  Spam
2         http://appbasic.jettons.co.uk/links/index.html       4  Spam
3      http://archive.yorkpress.co.uk/2003/11/6/25684...       4  Spam
4      http://acard4u.co.uk/product_reviews.php?cPath...       4  Spam
...                                                  ...     ...   ...
11995    http://archive.salisburyjournal.co.uk/2001/3/7/       4  Spam
11996  http://astore.amazon.co.uk/allezvinsfrenchr/de...       4  Spam
11997  http://archive.thisischeshire.co.uk/2000/1/14/...       4  Spam
11998  http://applerugs.co.uk/rugs/product_info.php?p...       4  Spam
11999  http://allgirltogaparty.co.uk/gallery2/main.ph...       4  Spam

[12000 rows x 3 columns]

In [7]:
data=[l2,l3,l4,l5]
urls = pd.concat(data)
urls = urls.rename({0: 'url'}, axis=1)
urls
urls

                                                     url  result        type
0            http://www.sinduscongoias.com.br/index.html       1  Defacement
1      http://www.sinduscongoias.com.br/index.php/ins...       1  Defacement
2      http://www.sinduscongoias.com.br/index.php/ins...       1  Defacement
3      http://www.sinduscongoias.com.br/index.php/ins...       1  Defacement
4      http://www.sinduscongoias.com.br/index.php/ins...       1  Defacement
...                                                  ...     ...         ...
11995    http://archive.salisburyjournal.co.uk/2001/3/7/       4        Spam
11996  http://astore.amazon.co.uk/allezvinsfrenchr/de...       4        Spam
11997  http://archive.thisischeshire.co.uk/2000/1/14/...       4        Spam
11998  http://applerugs.co.uk/rugs/product_info.php?p...       4        Spam
11999  http://allgirltogaparty.co.uk/gallery2/main.ph...       4        Spam

[129988 rows x 3 columns]

In [8]:
vectorizer = CountVectorizer(analyzer='char')
x = vectorizer.fit_transform(urls['url'])
x.shape

(129988, 133)

In [9]:
vectorizer.vocabulary_

{'h': 43,
 't': 55,
 'p': 51,
 ':': 25,
 '/': 14,
 'w': 58,
 '.': 13,
 's': 54,
 'i': 44,
 'n': 49,
 'd': 39,
 'u': 56,
 'c': 38,
 'o': 50,
 'g': 42,
 'a': 36,
 'm': 48,
 'b': 37,
 'r': 53,
 'e': 40,
 'x': 59,
 'l': 47,
 '1': 16,
 '-': 12,
 'v': 57,
 'q': 52,
 'j': 45,
 'f': 41,
 '9': 24,
 '0': 15,
 '2': 17,
 '8': 23,
 '3': 18,
 '7': 22,
 '6': 21,
 '5': 20,
 'k': 46,
 '?': 30,
 '=': 28,
 '_': 35,
 '&': 5,
 '4': 19,
 '*': 9,
 'y': 60,
 'z': 61,
 '%': 4,
 '#': 2,
 '\\': 33,
 'ส': 111,
 'น': 97,
 'ห': 112,
 'พ': 102,
 'ึ': 122,
 'ณ': 91,
 'ว': 109,
 'ล': 107,
 'ต': 93,
 'ฤ': 106,
 'ถ': 94,
 'ฎ': 86,
 'ฮ': 115,
 'บ': 98,
 'ศ': 110,
 'ฅ': 78,
 'ป': 99,
 'ุ': 124,
 'ฟ': 103,
 'ฝ': 101,
 'ฺ': 126,
 'ฐ': 88,
 'ด': 92,
 'ฦ': 108,
 'ท': 95,
 'ๅ': 129,
 'ฉ': 81,
 'ญ': 85,
 'ผ': 100,
 'ู': 125,
 'า': 118,
 'ะ': 116,
 '\uf1dc': 132,
 'ฬ': 113,
 'จ': 80,
 'อ': 114,
 'ไ': 128,
 'ธ': 96,
 'ั': 117,
 'ฒ': 90,
 'ร': 105,
 'ค': 77,
 '|': 63,
 'ำ': 119,
 'ช': 82,
 '๓': 131,
 'ื': 123,
 'ย': 104,
 'ี': 121,
 'ิ': 120,
 'ก': 74,
 'ฏ': 87,
 '่': 130,
 '$': 3,
 'ง': 79,
 'ฃ': 76,
 '!': 1,
 ',': 11,
 '+': 10,
 '(': 7,
 ')': 8,
 "'": 6,
 'ข': 75,
 'ฑ': 89,
 '~': 65,
 '@': 31,
 'ซ': 83,
 '\xa0': 67,
 '[': 32,
 ']': 34,
 '<': 27,
 '>': 29,
 'เ': 127,
 'ฌ': 84,
 '{': 62,
 '}': 64,
 ';': 26,
 ' ': 0,
 'ä': 69,
 '¸': 68,
 'š': 72,
 'å': 70,
 '\x8d': 66,
 'ˆ': 73,
 'ø': 71}

In [10]:
#lr = SVC()
clf = SVC()

In [11]:
scoring = {'accuracy': make_scorer(accuracy_score),
           'precision': make_scorer(precision_score, average = 'weighted'),
           'recall': make_scorer(recall_score, average = 'weighted'),
           'f1': make_scorer(f1_score, average = 'weighted')}

In [12]:
scores = cross_validate(clf, x, np.array(urls['result'].tolist()), cv=5,scoring=scoring,return_train_score=True)
scores

{'fit_time': array([27.75046921, 31.88363242, 30.26144361, 27.14818549, 25.57321763]),
 'score_time': array([3.59458518, 3.43965769, 2.80248713, 2.85166693, 2.70978856]),
 'test_accuracy': array([0.89872298, 0.94018771, 0.91945534, 0.89479555, 0.86463823]),
 'train_accuracy': array([0.94602366, 0.94558131, 0.95021637, 0.95669818, 0.95474608]),
 'test_precision': array([0.89634972, 0.93775911, 0.91845711, 0.88050806, 0.81594749]),
 'train_precision': array([0.9449224 , 0.94591918, 0.95090952, 0.95678665, 0.95487422]),
 'test_recall': array([0.89872298, 0.94018771, 0.91945534, 0.89479555, 0.86463823]),
 'train_recall': array([0.94602366, 0.94558131, 0.95021637, 0.95669818, 0.95474608]),
 'test_f1': array([0.89444734, 0.93719018, 0.90886124, 0.86996212, 0.82923556]),
 'train_f1': array([0.94177752, 0.94094034, 0.94643916, 0.9545208 , 0.95189745])}

In [13]:
print("The Fit Time is: ",scores['fit_time'].mean())
print("\n")
print("The Score Time is: ",scores['score_time'].mean())
print("\n")
print("The Train Accuracy score is: ",scores['train_accuracy'].mean())
print("\n")
print("The Train F1 score is: ",scores['train_f1'].mean())
print("\n")
print("The Train Precision score is: ",scores['train_precision'].mean())
print("\n")
print("The Train Recall score is: ",scores['train_recall'].mean())
print("\n")
print("The Test Accuracy score is: ",scores['test_accuracy'].mean())
print("\n")
print("The Test F1 score is: ",scores['test_f1'].mean())
print("\n")
print("The Test Precision score is: ",scores['test_precision'].mean())
print("\n")
print("The Test Recall score is: ",scores['test_recall'].mean())
print("\n")

The Fit Time is:  28.523389673233034


The Score Time is:  3.0796370983123778


The Train Accuracy score is:  0.9506531177146658


The Train F1 score is:  0.9471150523140841


The Train Precision score is:  0.9506823925731162


The Train Recall score is:  0.9506531177146658


The Test Accuracy score is:  0.9035599617953753


The Test F1 score is:  0.8879392872289393


The Test Precision score is:  0.889804299344757


The Test Recall score is:  0.9035599617953753